[env]
build_src_flags =
  -std=gnu11
  -Wall
  -Wextra
  -Werror

[env:esp32devkit_v1]
platform = espressif32@7.0.1
board = esp32doit-devkit-v1
framework = espidf
build_flags =
  -D BLINK_TARGET_ESP32
  -D BLINK_LED_PIN=GPIO_NUM_2
  -D BLINK_LED_ACTIVE_LOW=0
  -D BLINK_HALF_PERIOD_MS=500

[env:uno]
platform = atmelavr@5.3.0
board = uno
build_flags =
  -D BLINK_TARGET_AVR
  -D BLINK_LED_DDR=DDRB
  -D BLINK_LED_PORT=PORTB
  -D BLINK_LED_BIT=PB5
  -D BLINK_LED_ACTIVE_LOW=0
  -D BLINK_HALF_PERIOD_MS=500

[env:nucleo_f401re]
platform = ststm32@19.7.0
board = nucleo_f401re
framework = stm32cube
build_flags =
  -D BLINK_TARGET_STM32
  -D BLINK_LED_CLOCK_ENABLE=__HAL_RCC_GPIOA_CLK_ENABLE
  -D BLINK_LED_PORT=GPIOA
  -D BLINK_LED_PIN=GPIO_PIN_5
  -D BLINK_LED_ACTIVE_LOW=0
  -D BLINK_HALF_PERIOD_MS=500
