[platformio]
default_envs = esp32dev

[env]
framework = arduino
build_src_flags =
  -Wall
  -Wextra
  -Werror

[env:esp32dev]
platform = espressif32
board = esp32dev
build_flags = -D BLINK_LED_PIN=2

[env:uno]
platform = atmelavr
board = uno
build_flags = -D BLINK_LED_PIN=LED_BUILTIN

[env:nucleo_f401re]
platform = ststm32
board = nucleo_f401re
build_flags = -D BLINK_LED_PIN=LED_BUILTIN

[env:pico_rp2040]
platform = raspberrypi
board = pico
build_flags = -D BLINK_LED_PIN=LED_BUILTIN
